name: Atualizar Abastecimento

on:
  repository_dispatch:
    types: [atualizar]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Atualizar index.html
        run: python3 update.py
        env:
          NOME: ${{ github.event.client_payload.nome }}
          LANCHES: ${{ github.event.client_payload.lanches }}
          OBSERVACAO: ${{ github.event.client_payload.observacao }}

      - name: Commit e Push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add index.html
          git commit -m "Atualizar abastecimento do dia" || echo "Sem mudanças"
          git push
